### PR TITLE
[PLAT-354] Integration tests for vesting schedules

### PR DESCRIPTION
**Pull request by DidacSF**
## Description

This PR aims to add integration tests to all three different runtimes currently present in the node, these tests focus in the validation of different type of vesting schedules to ensure their proper behaviour.

## Type of changes

- [ ] `build`: Changes that affect the build system or external dependencies (eg, Cargo, Docker)
- [ ] `ci`: Changes to CI configuration
- [ ] `docs`: Changes to documentation only
- [ ] `feat`: Changes to add a new feature
- [ ] `fix`: Changes to fix a bug
- [ ] `refactor`: Changes that do not alter functionality
- [ ] `style`: Changes to format the code
- [x] `test`: Changes to add missing tests or correct existing tests

## Checklist

- [x] Tests for the changes have been added
- [x] ~Necessary documentation is added (if appropriate)~
- [x] Formatted with `cargo fmt --all`
- [x] Linted with `cargo clippy --all-features -- -D warnings`
- [x] Tested with `cargo test --workspace --all-features`

### CODE REVIEW

**Review by andyjsbell — COMMENTED** [review]
Looks good in covering our vesting requirements. 

However, there seems to be a large repetition of code here and maybe its not necessary.  I don't think this actually adds value to our runtime and as such not sure if it maybe should be somewhere else.  What was the purpose of this?  Were we looking at proving out whether our assumptions on how the vesting pallet works?  If so, should this be part of our runtime?  I think this would be best covered in a separate crate which contains only our integration tests. 

What I think would work here is cherry pick out the tests and drop them into what I am working in with regards to integration test crate in https://ajunanetwork.atlassian.net/browse/PLAT-186.   Does this make sense @DidacSF ?

**Comment by DidacSF** [comment]
> Looks good in covering our vesting requirements.
> 
> However, there seems to be a large repetition of code here and maybe its not necessary. I don't think this actually adds value to our runtime and as such not sure if it maybe should be somewhere else. What was the purpose of this? Were we looking at proving out whether our assumptions on how the vesting pallet works? If so, should this be part of our runtime? I think this would be best covered in a separate crate which contains only our integration tests.
> 
> What I think would work here is cherry pick out the tests and drop them into what I am working in with regards to integration test crate in https://ajunanetwork.atlassian.net/browse/PLAT-186. Does this make sense @DidacSF ?

Yeah, I do believe doing that would be better to be honest. In the end as you say, this tests are more of a proof-of-use for the vesting pallet than actual tests.

**Comment by cowboy-bebug** [comment]
LGTM! I agree these tests would look nicer as part of [PLAT-186](https://ajunanetwork.atlassian.net/browse/PLAT-186).

**Comment by DidacSF** [comment]
Closing PR and adding comment to PLAT-186 to take it into account when it's time to proceed with it.

**Pull request closed without merging**
