### PR TITLE
fix(cli): remove if for try runtime

### PR DESCRIPTION
**Pull request by cowboy-bebug**
## Description

Please describe your pull request and link relevant issues.

## Type of changes

- [ ] `build`: Changes that affect the build system or external dependencies (eg, Cargo, Docker)
- [ ] `ci`: Changes to CI configuration
- [ ] `docs`: Changes to documentation only
- [ ] `feat`: Changes to add a new feature
- [ ] `fix`: Changes to fix a bug
- [ ] `refactor`: Changes that do not alter functionality
- [ ] `style`: Changes to format the code
- [ ] `test`: Changes to add missing tests or correct existing tests

## Checklist

- [ ] Tests for the changes have been added
- [ ] Necessary documentation is added (if appropriate)
- [ ] Formatted with `cargo fmt --all`
- [ ] Linted with `cargo clippy --all-features --all-targets`
- [ ] Tested with `cargo test --workspace --all-features --all-targets`

### CODE REVIEW

**Comment by cowboy-bebug** [comment]
Both commands should work
```bash
cargo run --release --features=try-runtime --features=bajun --bin=bajun-para \
  try-runtime \
    --runtime=./target/release/wbuild/bajun-runtime/bajun_runtime.compact.compressed.wasm \
    --wasm-execution=compiled \
    --chain=./resources/bajun/bajun-raw.json \
    on-runtime-upgrade --checks live \
    --uri="ws://rpc-parachain.bajun.network:9944"

cargo run --release --features=try-runtime --features=ajuna --bin=ajuna-para \
  try-runtime \
    --runtime=./target/release/wbuild/ajuna-runtime/ajuna_runtime.compact.compressed.wasm \
    --wasm-execution=compiled \
    --chain=./resources/ajuna/ajuna-raw.json \
    on-runtime-upgrade --checks live \
    --uri="ws://rpc-parachain.ajuna.network:9944"
```
```

**Review by darkfriend77 — DISMISSED** [review]

**Comment by darkfriend77** [comment]
> Both commands should work
> 
> ```shell
> cargo run --release --features=try-runtime --features=bajun --bin=bajun-para \
>   try-runtime \
>     --runtime=./target/release/wbuild/bajun-runtime/bajun_runtime.compact.compressed.wasm \
>     --wasm-execution=compiled \
>     --chain=./resources/bajun/bajun-raw.json \
>     on-runtime-upgrade --checks live \
>     --uri="ws://rpc-parachain.bajun.network:9944"
> 
> cargo run --release --features=try-runtime --features=ajuna --bin=ajuna-para \
>   try-runtime \
>     --runtime=./target/release/wbuild/ajuna-runtime/ajuna_runtime.compact.compressed.wasm \
>     --wasm-execution=compiled \
>     --chain=./resources/ajuna/ajuna-raw.json \
>     on-runtime-upgrade --checks live \
>     --uri="ws://rpc-parachain.ajuna.network:9944"
> ```

Can you fix the error, so we can merge?

```
error[E0308]: mismatched types
   --> node/cli/src/para/command.rs:330:5
    |
194 | /      match &cli.subcommand {
195 | |          Some(Subcommand::BuildSpec(cmd)) => {
196 | |              let runner = cli.create_runner(cmd)?;
197 | |              runner.sync_run(|config| cmd.run(config.chain_spec, config.network))
...   |
330 | |/                 runner.async_run(|_| {
331 | ||                     Ok((
332 | ||                         cmd.run::<AjunaBlock, HostFunctionsOf<AjunaRuntimeExecutor>, _>(Some(
333 | ||                             timestamp_with_aura_info::<AjunaBlock>(6000),
...   ||
336 | ||                     ))
337 | ||                 })
    | ||__________________^ expected `()`, found enum `Result`
...   |
446 | |          },
447 | |      }
    | |______- expected this to be `()`
```

**Comment by cowboy-bebug** [comment]
@darkfriend77 When you run the command against bajun, you'll see this line fail:
https://github.com/ajuna-network/Ajuna/blob/26e1572836b8065514272a047a3506e81d254942/pallets/ajuna-awesome-avatars/src/migration/v5.rs#L279

@DidacSF will be able to help you out. It's most likely the data on bajun-kusama have changed since.

**Comment by DidacSF** [comment]
> @darkfriend77 When you run the command against bajun, you'll see this line fail:
> 
> https://github.com/ajuna-network/Ajuna/blob/26e1572836b8065514272a047a3506e81d254942/pallets/ajuna-awesome-avatars/src/migration/v5.rs#L279
> 
> @DidacSF will be able to help you out. It's most likely the data on bajun-kusama have changed since.

Yeah, I've updated the estimates using the latest data from Kusama, that should put us in a more accurate details when performing the migration

**Comment by darkfriend77** [comment]
> @darkfriend77 When you run the command against bajun, you'll see this line fail:
> 
> https://github.com/ajuna-network/Ajuna/blob/26e1572836b8065514272a047a3506e81d254942/pallets/ajuna-awesome-avatars/src/migration/v5.rs#L279
> 
> @DidacSF will be able to help you out. It's most likely the data on bajun-kusama have changed since.

Yep, I already did that locally to have it reflect the balun storage. However, this will fail for Rococo, so we will need to have it set in different versions. @cowboy-bebug @DidacSF

**Review by darkfriend77 — APPROVED** [review]
good

**Pull request merged**
